<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('students')->insert([
            [
                'school_id' => '2060283853',
                'id_number' => '202001408',
                'f_name' => 'John',
                'm_name' => 'A',
                'l_name' => 'Doe',
                'email' => 'john.doe@example.com',
                'program' => 'BSCSSE',
            ],
            [
                'school_id' => '2059401485',
                'id_number' => '202001345',
                'f_name' => 'Jane',
                'm_name' => 'B',
                'l_name' => 'Smith',
                'email' => 'jane.smith@example.com',
                'program' => 'BSCSSE',
            ],
            [
                'school_id' => '2073481209',
                'id_number' => '202002569',
                'f_name' => 'Chris',
                'm_name' => 'G',
                'l_name' => 'Walker',
                'email' => 'chris.walker@example.com',
                'program' => 'BSCSCC',
            ],
            [
                'school_id' => '2064891274',
                'id_number' => '202002340',
                'f_name' => 'Kim',
                'm_name' => 'H',
                'l_name' => 'Lee',
                'email' => 'kim.lee@example.com',
                'program' => 'BSCSDS',
            ],
            [
                'school_id' => '2093847201',
                'id_number' => '202003458',
                'f_name' => 'Alex',
                'm_name' => 'I',
                'l_name' => 'Johnson',
                'email' => 'alex.johnson@example.com',
                'program' => 'BSITWD',
            ],
            [
                'school_id' => '2084721903',
                'id_number' => '202003920',
                'f_name' => 'Pat',
                'm_name' => 'J',
                'l_name' => 'Brown',
                'email' => 'pat.brown@example.com',
                'program' => 'BSBAMM',
            ],
            [
                'school_id' => '2069374810',
                'id_number' => '202004301',
                'f_name' => 'Sam',
                'm_name' => 'K',
                'l_name' => 'Davis',
                'email' => 'sam.davis@example.com',
                'program' => 'BSBAEM',
            ],
            [
                'school_id' => '2057382904',
                'id_number' => '202004578',
                'f_name' => 'Taylor',
                'm_name' => 'L',
                'l_name' => 'Martinez',
                'email' => 'taylor.martinez@example.com',
                'program' => 'BSREM',
            ],
            [
                'school_id' => '2074839201',
                'id_number' => '202005673',
                'f_name' => 'Jordan',
                'm_name' => 'M',
                'l_name' => 'Harris',
                'email' => 'jordan.harris@example.com',
                'program' => 'ABPSY',
            ],
            [
                'school_id' => '2062384710',
                'id_number' => '202005230',
                'f_name' => 'Morgan',
                'm_name' => 'N',
                'l_name' => 'Clark',
                'email' => 'morgan.clark@example.com',
                'program' => 'BSA',
            ],
            [
                'school_id' => '2048293012',
                'id_number' => '202005902',
                'f_name' => 'Sydney',
                'm_name' => 'O',
                'l_name' => 'Lopez',
                'email' => 'sydney.lopez@example.com',
                'program' => 'BAFDT',
            ],
            [
                'school_id' => '2093017482',
                'id_number' => '202006401',
                'f_name' => 'Drew',
                'm_name' => 'P',
                'l_name' => 'Gonzalez',
                'email' => 'drew.gonzalez@example.com',
                'program' => 'ABMAD',
            ],
            [
                'school_id' => '2084729012',
                'id_number' => '202006890',
                'f_name' => 'Casey',
                'm_name' => 'Q',
                'l_name' => 'Wilson',
                'email' => 'casey.wilson@example.com',
                'program' => 'BSAN',
            ],
            [
                'school_id' => '2073028491',
                'id_number' => '202007123',
                'f_name' => 'Peyton',
                'm_name' => 'R',
                'l_name' => 'Moore',
                'email' => 'peyton.moore@example.com',
                'program' => 'ABMPSD',
            ],
            [
                'school_id' => '2069847302',
                'id_number' => '202007890',
                'f_name' => 'Dana',
                'm_name' => 'S',
                'l_name' => 'Taylor',
                'email' => 'dana.taylor@example.com',
                'program' => 'ABFVE',
            ],
            // Senior High School students with unique id_number values
            [
                'school_id' => '2048273012',
                'id_number' => '2021SHA01567',
                'f_name' => 'Bailey',
                'm_name' => 'T',
                'l_name' => 'Anderson',
                'email' => 'bailey.anderson@example.com',
                'program' => 'SHS-SE',
            ],
            [
                'school_id' => '2093847120',
                'id_number' => '2021SHA01789',
                'f_name' => 'Alexis',
                'm_name' => 'U',
                'l_name' => 'Thomas',
                'email' => 'alexis.thomas@example.com',
                'program' => 'SHS-MMA',
            ],
            [
                'school_id' => '2084729013',
                'id_number' => '2021SHA01234',
                'f_name' => 'Riley',
                'm_name' => 'V',
                'l_name' => 'Jackson',
                'email' => 'riley.jackson@example.com',
                'program' => 'SHS-ABM',
            ],
            [
                'school_id' => '2073028492',
                'id_number' => '2021SHA01568',
                'f_name' => 'Cameron',
                'm_name' => 'W',
                'l_name' => 'White',
                'email' => 'cameron.white@example.com',
                'program' => 'SHS-AP',
            ],
            [
                'school_id' => '2069847303',
                'id_number' => '2021SHA01890',
                'f_name' => 'Jordan',
                'm_name' => 'X',
                'l_name' => 'Lewis',
                'email' => 'jordan.lewis@example.com',
                'program' => 'SHS-A',
            ],
            [
                'school_id' => '2048273013',
                'id_number' => '2021SHA02123',
                'f_name' => 'Taylor',
                'm_name' => 'Y',
                'l_name' => 'Robinson',
                'email' => 'taylor.robinson@example.com',
                'program' => 'SHS-FD',
            ],
            [
                'school_id' => '2093847121',
                'id_number' => '2021SHA02456',
                'f_name' => 'Casey',
                'm_name' => 'Z',
                'l_name' => 'Davis',
                'email' => 'casey.davis@example.com',
                'program' => 'SHS-HUMMS',
            ],
            [
                'school_id' => '2084729014',
                'id_number' => '2021SHA02789',
                'f_name' => 'Sydney',
                'm_name' => 'AA',
                'l_name' => 'Garcia',
                'email' => 'sydney.garcia@example.com',
                'program' => 'SHS-RB',
            ],
        ]);
    }
}